import { type ClassValue, clsx } from 'clsx';
import { twMerge } from 'tailwind-merge';
import { generateReactHelpers } from '@uploadthing/react/hooks';

import { OurFileRouter } from '@/app/api/uploadthing/core';

export const { useUploadThing, uploadFiles } =
	generateReactHelpers<OurFileRouter>();

// generated by shadcn
export function cn(...inputs: ClassValue[]) {
	return twMerge(clsx(inputs));
}
